version: '3'
services:
  server:
    image: "nicom93/dockmon-server"
    environment:
      DM_PORT: 9090
  client:
    image: "nicom93/dockmon-client"
    ports:
      - "80:80"
    environment:
      PORT: 80
      PROXY: http://server:9090