version: '3'
services:
  server:
    image: "nicom93/dockmon-server"
    environment:
      DM_PORT: 9090
  client:
    image: "nicom93/dockmon-client"
    environment:
      port: 80
      serverPort: 9090